[package]
name = "domeos"
version = "0.1.0"
authors = ["Dom Williams <me@domwillia.ms>"]

[dependencies]
volatile = "0.2.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target = "spec.json"
output = "target/kernel.bin"
